default: &default
  app_host:            <%= ENV['APP_HOST'] %>
  secret_key_base:     <%= ENV['SECRET_KEY_BASE'] %>
  secret_key:          <%= ENV['SECRET_KEY'] %>
  secret_token:        <%= ENV['SECRET_TOKEN'] %>
  errbit:
    key:               <%= ENV['ERRBIT_KEY'] %>
    host:              <%= ENV['ERRBIT_HOST'] %>

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
